### ISSUE TITLE
Not able to parse structure variables having the same name as a user defined type using typedef

### ISSUE THREAD

**Issue by studywireless** [albertz/PyCParser#2]
Consider the below structure,

typedef struct
{
    int number;
}Number;

struct XYZ
{
    Number Number[10];
}xyz;

PyCParser is not able to parse the 2nd structure, its complaining about Number[10]. The above is a valid C declaration.

**Comment by albertz** [comment]
This is already fixed. (See a33fce5e.) (Better late than never.)
